### ISSUE TITLE
serialise date to number instead of string

### ISSUE THREAD

**Issue by samualtnorman** [lxsmnsyc/seroval#19]
surely it's better to serialise a date to the format `new Date(1682085024851)` instead of `new Date("2023-04-21T13:50:24.851Z")`?

the number is smaller and the string needs parsing.

I might be wrong though and there's something I'm missing. I'm curious if that's the case.

Thanks.

**Comment by lxsmnsyc** [comment]
This is mostly just to make the serialized `Date` in JS readable. There's not much difference betwen Unix timestamp and ISO-8601 except readability.

**Comment by samualtnorman** [comment]
is readable serialised data a goal of this repository?

**Comment by lxsmnsyc** [comment]
the serialized JS should be partially readable (disregarding variables of course). The JSON structure can be mangled but only to a degree that the serialization step doesn't lose perf.

**Comment by lxsmnsyc** [comment]
okay I forgot, the strong argument here is timezones.

**Comment by samualtnorman** [comment]
do timezones affect either format?

**Comment by lxsmnsyc** [comment]
@samualtnorman I believe Unix timestamp doesn't encode timezones, and only represents the local time of where it is interpreted. ISO string can represent timezone through offsets.

**Comment by samualtnorman** [comment]
all unix timestamps are UTC
