### ISSUE TITLE
Eventually drop `eval`?

### ISSUE THREAD

**Issue by AlexErrant** [lxsmnsyc/seroval#44]
`eval` is used [here](https://github.com/lxsmnsyc/seroval/blob/822af206c29c36b51cc5e6f24c0883b52bc0aa11/packages/seroval/src/core/tree/index.ts#L47), which unfortunately causes an error in sites which have a strict [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy). AFAIK the only way to get around this is to add [`unsafe-eval`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_eval_expressions) to the CSP, which, as the name suggests, is unsafe.

Is there any plan to move away from `eval`? Looking at the complexity of e.g. https://github.com/lxsmnsyc/seroval/blob/main/packages/seroval/src/core/context/serializer.ts I'm pretty sure the answer is "no", but thought I should ask anyway.

**Comment by lxsmnsyc** [comment]
if there's an alternative to `eval`, then yes that should be possible. Other than that, the answer would be "no".

The thing is, the data serialization format is in JS, so there's just no way we can evaluate those scripts without using `eval`.

**Comment by millette** [comment]
Closed because no `eval ` alternatives were evaluated? (no pun intended).

**Comment by AlexErrant** [comment]
I'm assuming any direct workaround like `Function()` would be covered by [`unsafe-eval`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_eval_expressions) since it would be targeted by hackers.

Indirectly, perhaps Seroval could be loaded in a webworker/iframe on a different origin where `unsafe-eval` has _not_ been set. Of course, now you need to figure out how to transfer the deserialized data to the original origin... some data is ["transferrable"](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Transferable_objects), but not all. This would probably break streaming and other Seroval features.

There's a [`trusted-types-eval`](https://github.com/w3c/webappsec-csp/pull/665) that's being proposed for [Content Security Policy Level 3](https://www.w3.org/TR/CSP3/), but of course it's not out yet. And even when it lands, support won't be universal.

Finally, there's tRPC.

**Comment by lxsmnsyc** [comment]
> Indirectly, perhaps Seroval could be loaded in a webworker/iframe on a different origin

You had me at "webworker". Seroval isn't just a server-client serialization library, it's a runtime-to-runtime serialization library.
