### ISSUE TITLE
TanStack Router/Start Configuration

### ISSUE THREAD

**Issue by aretrace** [lxsmnsyc/seroval#46]
TanStack Router has custom cross network boundary serialization [support](https://tanstack.com/router/latest/docs/framework/react/guide/ssr#data-transformers):
```js
import { SuperJSON } from 'superjson'

const router = createRouter({
  transformer: SuperJSON,
})
```
How could you set up `seroval` on TanStack Router/Start?

**Comment by lxsmnsyc** [comment]
@aretrace I think this works?

```js
import { serialize, deserialize } from 'seroval';

const transformer = {
  stringify: serialize,
  parse: deserialize,
};
```

alternatively, there's also `toJSON` and `fromJSON`. Unfortunately, seems like the interface only supports synchronous serialization.
